from sqlalchemy import String, Float, Boolean, Text, JSON, Integer
from sqlalchemy.orm import Mapped, mapped_column
from tourism_crawler.models.base import Base, TimestampMixin


class PlaceModel(Base, TimestampMixin):
    __tablename__ = "places"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    english_name: Mapped[str] = mapped_column(String(255), nullable=True)
    category: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    subcategory: Mapped[str] = mapped_column(String(100), nullable=True)
    description: Mapped[str] = mapped_column(Text, nullable=True)
    full_description: Mapped[str] = mapped_column(Text, nullable=True)
    address: Mapped[str] = mapped_column(Text, nullable=False)
    commune: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    district: Mapped[str] = mapped_column(String(100), default="Tri Tôn")
    province: Mapped[str] = mapped_column(String(100), default="An Giang")
    country: Mapped[str] = mapped_column(String(100), default="Việt Nam")
    latitude: Mapped[float] = mapped_column(Float, nullable=False)
    longitude: Mapped[float] = mapped_column(Float, nullable=False)
    google_maps_url: Mapped[str] = mapped_column(Text, nullable=True)
    website: Mapped[str] = mapped_column(String(500), nullable=True)
    facebook: Mapped[str] = mapped_column(String(500), nullable=True)
    tiktok: Mapped[str] = mapped_column(String(500), nullable=True)
    youtube: Mapped[str] = mapped_column(String(500), nullable=True)
    phone: Mapped[str] = mapped_column(String(50), nullable=True)
    email: Mapped[str] = mapped_column(String(100), nullable=True)
    opening_hours: Mapped[str] = mapped_column(String(100), nullable=True)
    ticket_price: Mapped[str] = mapped_column(String(200), nullable=True)
    parking_fee: Mapped[str] = mapped_column(String(200), nullable=True)
    average_cost: Mapped[str] = mapped_column(String(200), nullable=True)
    rating: Mapped[float] = mapped_column(Float, default=0.0)
    review_count: Mapped[int] = mapped_column(Integer, default=0)
    best_time: Mapped[str] = mapped_column(String(200), nullable=True)
    best_season: Mapped[str] = mapped_column(String(200), nullable=True)
    recommended_duration: Mapped[str] = mapped_column(String(100), nullable=True)
    tags: Mapped[dict] = mapped_column(JSON, default=list)
    images: Mapped[dict] = mapped_column(JSON, default=dict)
    videos: Mapped[dict] = mapped_column(JSON, default=list)
    facilities: Mapped[dict] = mapped_column(JSON, default=list)
    accessibility: Mapped[str] = mapped_column(Text, nullable=True)
    has_parking: Mapped[bool] = mapped_column(Boolean, default=True)
    has_wifi: Mapped[bool] = mapped_column(Boolean, default=False)
    has_toilet: Mapped[bool] = mapped_column(Boolean, default=True)
    has_restaurant: Mapped[bool] = mapped_column(Boolean, default=False)
    has_hotel: Mapped[bool] = mapped_column(Boolean, default=False)
    children_friendly: Mapped[bool] = mapped_column(Boolean, default=True)
    family_friendly: Mapped[bool] = mapped_column(Boolean, default=True)
    pet_friendly: Mapped[bool] = mapped_column(Boolean, default=False)
    drone_allowed: Mapped[bool] = mapped_column(Boolean, default=True)
    status: Mapped[str] = mapped_column(String(50), default="verified")
    confidence_score: Mapped[float] = mapped_column(Float, default=100.0)
    sources_count: Mapped[int] = mapped_column(Integer, default=3)
